name: Keep Streamlit Alive

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
        - run: curl https://india-trade-dashboard.streamlit.app/
